disabled_rules: # rule identifiers to exclude from running
  - line_length
  - large_tuple
  - file_length
  - type_body_length
  - todo
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - weak_delegate